# Generated by Django 5.1.1 on 2024-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('categorizing', 'Categorizing'), ('done', 'Done'), ('error', 'Error')], default='transcribing', max_length=32)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('emotional_tone', models.CharField(blank=True, choices=[('neural', 'Neural'), ('positive', 'Positive'), ('negative', 'Negative'), ('angry', 'Angry')], max_length=32, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='calls', to='categories.category')),
            ],
        ),
    ]
