# Generated by Django 5.1.1 on 2024-09-25 06:02

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='audio',
            field=models.FileField(storage=core.storages.ExternalMediaStorage(), upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('categorizing', 'Categorizing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=32),
        ),
    ]
