# Generated by Django 5.1.1 on 2024-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_call_audio_alter_call_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='status',
        ),
        migrations.AddField(
            model_name='call',
            name='qa_for_location_worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='qa_for_name_worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='transcription_worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='zero_shot_classification_worked',
            field=models.BooleanField(default=False),
        ),
    ]
