# Generated by Django 5.1.1 on 2024-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_remove_call_status_call_qa_for_location_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='zero_shot_classification_finish_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
