# Generated by Django 5.1.1 on 2024-10-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_zero_shot_classification_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='emotional_tone',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('positive', 'Positive'), ('negative', 'Negative'), ('angry', 'Angry')], max_length=32, null=True),
        ),
    ]
