# Generated by Django 5.1.1 on 2024-09-29 03:08

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    Category.objects.bulk_create([
        Category(title="Visa and Passport Services", points=[
            "Visa application procedures",
            "Passport renewal",
            "Required documents for applications",
            "Document processing times",
            "Visa fees and payments",
            "Availability of expedited processing"
        ]),
        Category(title="Diplomatic Inquiries", points=[
            "Political issues between countries",
            "Diplomatic exchanges",
            "International agreements and treaties",
            "Resolution of international conflicts",
            "Cooperation in the field of security",
        ]),
        Category(title="Travel Advisories", points=[
            "Security warnings for destination countries",
            "Information on natural disasters",
            "Updates on epidemic situations",
            "Health and vaccination recommendations",
            "Local laws and customs guidelines",
        ]),
        Category(title="Consular Assistance", points=[
            "Assistance to citizens abroad",
            "Issuance of powers of attorney and documents",
            "Support in case of arrest or detention",
            "Fine remission and legal assistance",
            "Repatriation and emergency return",
        ]),
        Category(title="Trade and Economic Cooperation", points=[
            "Investment opportunities",
            "Trade agreements and regulations",
            "Cooperation in technology and innovation",
            "Support for small and medium enterprises",
            "Market analysis and economic trends",
        ]),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_code=migrations.RunPython.noop),
    ]
