# Generated by Django 5.1.1 on 2024-10-01 15:51

from django.db import migrations, models


def set_candidate_labels(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    for category in Category.objects.all():
        category.candidate_labels = [category.title]
        if category.points:
            category.candidate_labels.extend(category.points)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="candidate_labels",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(set_candidate_labels, migrations.RunPython.noop),
    ]
